INSERT INTO background_musics (title, artist, description, preview_url, full_url) VALUES
('Monkeys Spinning Monkeys', 'Kevin MacLeod', ARRAY['Fun', 'Playful'], NULL, NULL),
('Hyperfun', 'Kevin MacLeod', ARRAY['Fun', 'Upbeat'], NULL, NULL),
('If I Had a Chicken', 'Kevin MacLeod', ARRAY['Playful', 'Happy'], NULL, NULL),
('Carefree', 'Kevin MacLeod', ARRAY['Chill', 'Happy'], NULL, NULL),
('Fluffing a Duck', 'Kevin MacLeod', ARRAY['Fun', 'Playful'], NULL, NULL),
('Life of Riley', 'Kevin MacLeod', ARRAY['Chill', 'Happy'], NULL, NULL),
('Happy Bee', 'Kevin MacLeod', ARRAY['Upbeat', 'Happy'], NULL, NULL),
('Amazing Plan', 'Kevin MacLeod', ARRAY['Fun', 'Playful'], NULL, NULL),
('Sneaky Snitch', 'Kevin MacLeod', ARRAY['Playful', 'Fun'], NULL, NULL),
('The Builder', 'Kevin MacLeod', ARRAY['Playful', 'Fun'], NULL, NULL),
('Marty Gots a Plan', 'Kevin MacLeod', ARRAY['Fun', 'Playful'], NULL, NULL),
('Scheming Weasel (faster version)', 'Kevin MacLeod', ARRAY['Fun', 'Playful'], NULL, NULL),
('Look Busy', 'Kevin MacLeod', ARRAY['Upbeat', 'Fun'], NULL, NULL),
('Sneaky Adventure', 'Kevin MacLeod', ARRAY['Fun', 'Playful'], NULL, NULL),
('The Ice Giants', 'Kevin MacLeod', ARRAY['Epic', 'Cinematic'], NULL, NULL),
('Strength of the Titans', 'Kevin MacLeod', ARRAY['Epic', 'Cinematic'], NULL, NULL),
('Killers', 'Kevin MacLeod', ARRAY['Epic', 'Cinematic'], NULL, NULL),
('Americana', 'Kevin MacLeod', ARRAY['Epic', 'Upbeat'], NULL, NULL),
('Hero Down', 'Kevin MacLeod', ARRAY['Epic', 'Dramatic'], NULL, NULL),
('For the Fallen', 'Kevin MacLeod', ARRAY['Epic', 'Emotional'], NULL, NULL),
('Second Coming - no percussion', 'Kevin MacLeod', ARRAY['Epic', 'Upbeat'], NULL, NULL),
('This House', 'Kevin MacLeod', ARRAY['Horror', 'Scary'], NULL, NULL),
('Hitman', 'Kevin MacLeod', ARRAY['Scary', 'Epic'], NULL, NULL),
('Deep Horrors', 'Kevin MacLeod', ARRAY['Horror', 'Scary'], NULL, NULL),
('Gathering Darkness', 'Kevin MacLeod', ARRAY['Scary', 'Horror'], NULL, NULL),
('Classic Horror 1', 'Kevin MacLeod', ARRAY['Horror', 'Scary'], NULL, NULL),
('Classic Horror 2', 'Kevin MacLeod', ARRAY['Scary', 'Horror'], NULL, NULL),
('Classic Horror 3', 'Kevin MacLeod', ARRAY['Horror', 'Scary'], NULL, NULL),
('Resignation', 'Kevin MacLeod', ARRAY['Calm', 'Emotional'], NULL, NULL),
('Heartwarming', 'Kevin MacLeod', ARRAY['Romantic', 'Happy'], NULL, NULL),
('At Rest', 'Kevin MacLeod', ARRAY['Peaceful', 'Calm'], NULL, NULL),
('Avec Soin', 'Kevin MacLeod', ARRAY['Romantic', 'Calm'], NULL, NULL),
('The Parting', 'Kevin MacLeod', ARRAY['Emotional', 'Romantic'], NULL, NULL),
('Thinking of You', 'Kevin MacLeod', ARRAY['Romantic', 'Calm'], NULL, NULL);