import type { Metadata } from "next";
import { ReactNode } from "react";
import { Rajdhani } from "next/font/google";
import ConditionalHeader from "@/components/public/header/ConditionalHeader";
import ConditionalMain from "@/components/public/ConditionalMain";
import { Analytics } from "@vercel/analytics/next";
import {AuthProvider} from "@/context/AuthContext";
import "./globals.css";

const defaultFont = Rajdhani({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${defaultFont.className} antialiased`}
            >
                <AuthProvider>
                    <div className="min-h-screen">
                        <ConditionalHeader/>
                        <ConditionalMain>
                            {children}
                        </ConditionalMain>
                    </div>
                </AuthProvider>
                <Analytics/>
            </body>
        </html>
    );
}
