import type { Metadata } from "next";
import { ReactNode } from "react";
import { Rajdhani } from "next/font/google";
import ConditionalHeader from "@/components/public/ConditionalHeader";
import ConditionalMain from "@/components/public/ConditionalMain";
import ApiPreloader from "@/components/public/ApiPreloader";
import "./globals.css";

const defaultFont = Rajdhani({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${defaultFont.className} antialiased`}
            >
                <ApiPreloader />
                <div className="min-h-screen">
                    <ConditionalHeader/>
                    <ConditionalMain>
                        {children}
                    </ConditionalMain>
                </div>
            </body>
        </html>
    );
}
